### ISSUE TITLE
Drop upper bound on base?

### ISSUE THREAD

**Issue by andreasabel** [byorgey/split#15]
`split` is a stable package and is very likely to work with future GHC versions just the same.  The upper bound on `base` however requires intervention with each release (or first candidate release) of a new major GHC version.  And those happen disturbingly often.

Could we do without an upper bound on `base`?  There are some risks:
1. `split` could fail to compile with a future GHC.
2. `split` could malfunction with a future GHC because the semantics of a `base`-function was changed under the hood.

Let's assess these risks:
1. This isn't worse than the status quo.  On the countrary, with an upper bound on `base`, the package is _bound to fail_ at a major GHC release, where without an upper bound it only _may_ fail to compile.
2. This risk can be mitigated by a CI that automatically tests with new GHC releases.  `split` has a thorough testsuite that is run by CI.  CI could be modified to automatically pick up the latest GHC via `ghcup`.

I would think that we are better off without an upper bound on `base` for `split`.  If this is wanted, I can look into changing CI to run with the latest GHC.

**Comment by byorgey** [comment]
Hi Andreas, thanks for nudging me to think about this and for writing up a clear assessment of the pros and cons.  I think I agree with you that we should get rid of the upper bound on `base`.

If there is a way to get CI to run automatically with the latest GHC, that would be cool, but I don't think that is a showstopper.
