### ISSUE TITLE
Extend last chunksOf chunk variant

### ISSUE THREAD

**Issue by noughtmare** [byorgey/split#16]
I recently needed a version of `chunksOf` which pads the last chunk such that all chunks are exactly the same size. If there was a function like this:

```haskell
rightPad :: a -> Int -> [a] -> [a]
rightPad x n xs = foldr (\x go m -> x : go (m + 1)) (\m -> replicate (n - m) x) xs 0
```

Then it is easy to implement my desired function like this:

```haskell
chunksOfExtend :: a -> Int -> [a] -> [[a]]
chunksOfExtend x n = map (rightPad x n) . chunksOf n
```

**Comment by byorgey** [comment]
`chunksOfExtend` does sound like a useful function; I'm open to pull requests.

Isn't there a simpler way to implement `rightPad`?  I have been staring at it for a few minutes and I still can't understand how it works.  I also wonder if that is the best way to implement `chunksOfExtend`, or if there is a more direct way to do it that doesn't require re-traversing every chunk.

**Comment by noughtmare** [comment]
My idea was that the map should fuse and that the padding counter would be the same as the chunking counter, so it should be very fast in practice. But I will do some benchmarking and inspecting the core to see if that really happens.

**Comment by noughtmare** [comment]
Here's some code I wrote which I believe is both a good consumer and a good producer and each element list is a good producer for fusion (the existing `chunksOf` is not a good consumer I believe):

```haskell
newtype Build a = Build (forall b. (a -> b -> b) -> b -> b)

instance Semigroup (Build a) where
  Build b1 <> Build b2 = Build $ \c n -> b1 c (b2 c n)

instance Monoid (Build a) where
  mempty = Build (\_ n -> n)

pureBuild :: a -> Build a
pureBuild x = Build $ \c n -> c x n

replicateBuild :: Int -> a -> Build a
replicateBuild k x = Build (go k) where
  go 0 c n = n
  go k c n = c x (go (k - 1) c n)

runBuild :: Build a -> [a]
runBuild (Build b) = build b

chunksOf :: forall a. Int -> [a] -> [[a]]
chunksOf n xs = build (\c1 n1 -> foldr (cons c1) (nil c1 n1) xs mempty n)
  where
    cons :: ([a] -> lst1 -> lst1) -> a -> (Build a -> Int -> lst1) -> Build a -> Int -> lst1
    cons c1 x go k 0 = runBuild k `c1` go (pureBuild x) (n - 1)
    cons c1 x go k i = go (k <> pureBuild x) (i - 1)

    nil :: ([a] -> lst1 -> lst1) -> lst1 -> Build a -> Int -> lst1
    nil c1 n1 k i = runBuild k `c1` n1
{-# INLINE chunksOf #-}

chunksOfExtend :: forall a. a -> Int -> [a] -> [[a]]
chunksOfExtend x n xs = build (\c1 n1 -> foldr (cons c1) (nil c1 n1) xs mempty n)
  where
    cons :: ([a] -> lst1 -> lst1) -> a -> (Build a -> Int -> lst1) -> Build a -> Int -> lst1
    cons c1 x go k 0 = runBuild k `c1` (go (pureBuild x) $! n - 1)
    cons c1 x go k i = go (k <> pureBuild x) $! i - 1

    nil :: ([a] -> lst1 -> lst1) -> lst1 -> Build a -> Int -> lst1
    nil c1 n1 k i = runBuild (k <> replicateBuild i x) `c1` n1
{-# INLINE chunksOfExtend #-}
```

I have confirmed that this does speed up a benchmark I have, but I will do some more investigation.

**Comment by byorgey** [comment]
I see, very cool!

**Comment by noughtmare** [comment]
It turns out that it wasn't true that all the chunks are good producers for fusion. Now, I don't even think that is really possible. Instead an alternative for my use-case is a function that applies a left fold over all chunks explicitly:

```haskell
foldlChunksOf :: (b foldlChunksOf :: (b -> a -> b) -> b -> Int -> [a] -> [b]
foldlChunksOf k z n xs = build helper where
  helper buildCons buildNil = foldr foldCons foldNil xs n z where
    foldNil = \_ s -> s `buildCons` buildNil
    foldCons x' go = \i x -> if i == 0 then x `buildCons` go (n - 1) (z `k` x') else go (i - 1) (x `k` x')
{-# INLINE foldlChunksOf #-}-> a -> b) -> b -> Int -> [a] -> [b]
```

Unfortunately, this doesn't feel as nice as a normal `chunksOf` function.
