### ISSUE TITLE
Use doctest to check examples?

### ISSUE THREAD

**Issue by andreasabel** [byorgey/split#19]
@byorgey Would you be open to convert the examples in the haddocks into doctest form?
They could be checked via `cabal repl -w doctest --repl-options=-w` then.

In the rendered docs, they would be looking like in the following picture for `splitWhen`, while the current style is the one of `endBy`.

<img width="900" alt="Screenshot 2023-09-04 at 20 18 05" src="https://github.com/byorgey/split/assets/1155218/99855720-0435-497d-8b8e-10ddc8e7d8c2">

(Got here because I wondered what `splitWhen` would be doing with consecutive separators---see added second example.)

**Comment by byorgey** [comment]
Yes, excellent idea!  I think when I wrote this library doctests weren't a thing (or maybe I just didn't know about them).  I can get around to doing the conversion soon, or of course I'm happy to accept a PR.

**Comment by byorgey** [comment]
Released to Hackage as `split-0.2.4`.
