### ISSUE TITLE
Support GHC 8.10.1

### ISSUE THREAD

**Issue by asr** [byorgey/split#7]
GHC 8.10.1-rc1 was [announced](https://mail.haskell.org/pipermail/ghc-devs/2020-January/018530.html).  I could install `split` using this version of GHC. Please bump the base bound to <4.15 and release a new version or revision on Hackage.

Blocking https://github.com/agda/agda/issues/4242.

**Comment by byorgey** [comment]
Released `split-0.2.3.4` to Hackage which supports GHC 8.10.

**Comment by asr** [comment]
Great! Thanks!
