### ISSUE TITLE
Support 9.0.1

### ISSUE THREAD

**Issue by asr** [byorgey/split#9]
GHC 9.0.1 was released. I could install `split` using this version of GHC by bumping the `base`upper bound to `< 4.16`. Please make this revision on Hackage.

Blocking agda/agda#4955.

**Comment by byorgey** [comment]
Updated in https://github.com/byorgey/split/commit/e2378c4803432dd1177e54d66a43d0bbae7da520 . Currently trying to wrangle CI to build it before uploading to Hackage.

**Comment by andreasabel** [comment]
> Currently trying to wrangle CI to build it before uploading to Hackage

I submitted PR #10 to updated CI to the latest supported versions there (8.8.4 and 8.10.3) and the cabal file `tested-with` to 8.8.4 and 8.10.4.
(These changes are _revision_-compatible, new _release_ doesn't seem necessary.)

**Comment by asr** [comment]
Blocking https://github.com/agda/fix-whitespace/issues/13.

**Comment by jrp2014** [comment]
It'd be great if the base bounds could be relaxed for 9.0.1

**Comment by andreasabel** [comment]
Thanks for merging #10.  I came minutes too late to update CI to 8.10.4 and 9.0.1, but did this in PR #12 now.

**Comment by byorgey** [comment]
The latest revision to `split-0.2.3.4` on Hackage now supports GHC 9.0.  Sorry for the delay!
